# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grand.federated_pb2 as message__pb2


class grpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendState = channel.unary_unary(
                '/message.grpcService/sendState',
                request_serializer=message__pb2.SelectedStates.SerializeToString,
                response_deserializer=message__pb2.GlobalState.FromString,
                )
        self.valSetup = channel.unary_unary(
                '/message.grpcService/valSetup',
                request_serializer=message__pb2.clientInformation.SerializeToString,
                response_deserializer=message__pb2.EmptyResponse.FromString,
                )
        self.getGlobalModel = channel.unary_unary(
                '/message.grpcService/getGlobalModel',
                request_serializer=message__pb2.EmptyResponse.SerializeToString,
                response_deserializer=message__pb2.GlobalState.FromString,
                )


class grpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def valSetup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getGlobalModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_grpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendState': grpc.unary_unary_rpc_method_handler(
                    servicer.sendState,
                    request_deserializer=message__pb2.SelectedStates.FromString,
                    response_serializer=message__pb2.GlobalState.SerializeToString,
            ),
            'valSetup': grpc.unary_unary_rpc_method_handler(
                    servicer.valSetup,
                    request_deserializer=message__pb2.clientInformation.FromString,
                    response_serializer=message__pb2.EmptyResponse.SerializeToString,
            ),
            'getGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.getGlobalModel,
                    request_deserializer=message__pb2.EmptyResponse.FromString,
                    response_serializer=message__pb2.GlobalState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.grpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class grpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.grpcService/sendState',
            message__pb2.SelectedStates.SerializeToString,
            message__pb2.GlobalState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def valSetup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.grpcService/valSetup',
            message__pb2.clientInformation.SerializeToString,
            message__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.grpcService/getGlobalModel',
            message__pb2.EmptyResponse.SerializeToString,
            message__pb2.GlobalState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
